[workspace]
resolver = "2"
members = [
  "crates/oxidean-api",
  "crates/oxidean-cli",
  "crates/oxidean-core",
  "crates/oxidean-db",
  "crates/oxidean-git",
  "crates/oxidean-runner",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
