/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRouteImport } from './routes/$owner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as OwnerIndexRouteImport } from './routes/$owner.index'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as OwnerPackagesRouteImport } from './routes/$owner.packages'
import { Route as OwnerSettingsRouteImport } from './routes/$owner.settings'
import { Route as AdminAuthRouteImport } from './routes/admin/auth'
import { Route as AdminLfsRouteImport } from './routes/admin/lfs'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminRunnersRouteImport } from './routes/admin/runners'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as OrgsNewRouteImport } from './routes/orgs.new'
import { Route as SettingsEmailsRouteImport } from './routes/settings/emails'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSshKeysRouteImport } from './routes/settings/ssh-keys'
import { Route as SettingsTokensRouteImport } from './routes/settings/tokens'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupCredentialsRouteImport } from './routes/setup.credentials'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoActionsRouteImport } from './routes/$owner.$repo.actions'
import { Route as OwnerRepoActivityRouteImport } from './routes/$owner.$repo.activity'
import { Route as OwnerRepoBranchesRouteImport } from './routes/$owner.$repo.branches'
import { Route as OwnerRepoForkRouteImport } from './routes/$owner.$repo.fork'
import { Route as OwnerRepoForksRouteImport } from './routes/$owner.$repo.forks'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo.issues'
import { Route as OwnerRepoPackagesRouteImport } from './routes/$owner.$repo.packages'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoReleasesRouteImport } from './routes/$owner.$repo.releases'
import { Route as OwnerRepoSearchRouteImport } from './routes/$owner.$repo.search'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner.$repo.settings'
import { Route as OwnerRepoStargazersRouteImport } from './routes/$owner.$repo.stargazers'
import { Route as OwnerRepoTagsRouteImport } from './routes/$owner.$repo.tags'
import { Route as OwnerRepoWatchersRouteImport } from './routes/$owner.$repo.watchers'
import { Route as OwnerSettingsIndexRouteImport } from './routes/$owner.settings.index'
import { Route as OwnerSettingsLabelsRouteImport } from './routes/$owner.settings.labels'
import { Route as OwnerSettingsMembersRouteImport } from './routes/$owner.settings.members'
import { Route as SettingsTokensIndexRouteImport } from './routes/settings/tokens.index'
import { Route as SettingsTokensNewRouteImport } from './routes/settings/tokens.new'
import { Route as OwnerRepoActionsIndexRouteImport } from './routes/$owner.$repo.actions.index'
import { Route as OwnerRepoActionsRunRouteImport } from './routes/$owner.$repo.actions.$run'
import { Route as OwnerRepoBlameSplatRouteImport } from './routes/$owner.$repo.blame.$'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner.$repo.blob.$'
import { Route as OwnerRepoCommitShaRouteImport } from './routes/$owner.$repo.commit.$sha'
import { Route as OwnerRepoCommitsSplatRouteImport } from './routes/$owner.$repo.commits.$'
import { Route as OwnerRepoCompareSplatRouteImport } from './routes/$owner.$repo.compare.$'
import { Route as OwnerRepoDeleteSplatRouteImport } from './routes/$owner.$repo.delete.$'
import { Route as OwnerRepoEditSplatRouteImport } from './routes/$owner.$repo.edit.$'
import { Route as OwnerRepoIssuesIndexRouteImport } from './routes/$owner.$repo.issues.index'
import { Route as OwnerRepoIssuesNRouteImport } from './routes/$owner.$repo.issues.$n'
import { Route as OwnerRepoIssuesLabelsRouteImport } from './routes/$owner.$repo.issues.labels'
import { Route as OwnerRepoIssuesNewRouteImport } from './routes/$owner.$repo.issues.new'
import { Route as OwnerRepoMkdirSplatRouteImport } from './routes/$owner.$repo.mkdir.$'
import { Route as OwnerRepoNewSplatRouteImport } from './routes/$owner.$repo.new.$'
import { Route as OwnerRepoPullNRouteImport } from './routes/$owner.$repo.pull.$n'
import { Route as OwnerRepoPullsIndexRouteImport } from './routes/$owner.$repo.pulls.index'
import { Route as OwnerRepoPullsNewRouteImport } from './routes/$owner.$repo.pulls.new'
import { Route as OwnerRepoReleasesIndexRouteImport } from './routes/$owner.$repo.releases.index'
import { Route as OwnerRepoReleasesTagRouteImport } from './routes/$owner.$repo.releases.$tag'
import { Route as OwnerRepoReleasesNewRouteImport } from './routes/$owner.$repo.releases.new'
import { Route as OwnerRepoSettingsActionsRouteImport } from './routes/$owner.$repo.settings.actions'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner.$repo.tree.$'
import { Route as OwnerRepoUploadSplatRouteImport } from './routes/$owner.$repo.upload.$'
import { Route as SettingsTokensNewIndexRouteImport } from './routes/settings/tokens.new.index'
import { Route as SettingsTokensNewFineGrainedRouteImport } from './routes/settings/tokens.new.fine-grained'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/$owner',
  path: '/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPackagesRoute = OwnerPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLfsRoute = AdminLfsRouteImport.update({
  id: '/admin/lfs',
  path: '/admin/lfs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRunnersRoute = AdminRunnersRouteImport.update({
  id: '/admin/runners',
  path: '/admin/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailsRoute = SettingsEmailsRouteImport.update({
  id: '/settings/emails',
  path: '/settings/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSshKeysRoute = SettingsSshKeysRouteImport.update({
  id: '/settings/ssh-keys',
  path: '/settings/ssh-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCredentialsRoute = SetupCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SetupRoute,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoActionsRoute = OwnerRepoActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoActivityRoute = OwnerRepoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBranchesRoute = OwnerRepoBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoForkRoute = OwnerRepoForkRouteImport.update({
  id: '/fork',
  path: '/fork',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoForksRoute = OwnerRepoForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPackagesRoute = OwnerRepoPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoReleasesRoute = OwnerRepoReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSearchRoute = OwnerRepoSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoStargazersRoute = OwnerRepoStargazersRouteImport.update({
  id: '/stargazers',
  path: '/stargazers',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoTagsRoute = OwnerRepoTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoWatchersRoute = OwnerRepoWatchersRouteImport.update({
  id: '/watchers',
  path: '/watchers',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerSettingsIndexRoute = OwnerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsLabelsRoute = OwnerSettingsLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const OwnerSettingsMembersRoute = OwnerSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OwnerSettingsRoute,
} as any)
const SettingsTokensIndexRoute = SettingsTokensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTokensRoute,
} as any)
const SettingsTokensNewRoute = SettingsTokensNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsTokensRoute,
} as any)
const OwnerRepoActionsIndexRoute = OwnerRepoActionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoActionsRoute,
} as any)
const OwnerRepoActionsRunRoute = OwnerRepoActionsRunRouteImport.update({
  id: '/$run',
  path: '/$run',
  getParentRoute: () => OwnerRepoActionsRoute,
} as any)
const OwnerRepoBlameSplatRoute = OwnerRepoBlameSplatRouteImport.update({
  id: '/blame/$',
  path: '/blame/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitShaRoute = OwnerRepoCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsSplatRoute = OwnerRepoCommitsSplatRouteImport.update({
  id: '/commits/$',
  path: '/commits/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCompareSplatRoute = OwnerRepoCompareSplatRouteImport.update({
  id: '/compare/$',
  path: '/compare/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoDeleteSplatRoute = OwnerRepoDeleteSplatRouteImport.update({
  id: '/delete/$',
  path: '/delete/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoEditSplatRoute = OwnerRepoEditSplatRouteImport.update({
  id: '/edit/$',
  path: '/edit/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesIndexRoute = OwnerRepoIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoIssuesNRoute = OwnerRepoIssuesNRouteImport.update({
  id: '/$n',
  path: '/$n',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoIssuesLabelsRoute = OwnerRepoIssuesLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoIssuesNewRoute = OwnerRepoIssuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoMkdirSplatRoute = OwnerRepoMkdirSplatRouteImport.update({
  id: '/mkdir/$',
  path: '/mkdir/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoNewSplatRoute = OwnerRepoNewSplatRouteImport.update({
  id: '/new/$',
  path: '/new/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullNRoute = OwnerRepoPullNRouteImport.update({
  id: '/pull/$n',
  path: '/pull/$n',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsIndexRoute = OwnerRepoPullsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoPullsRoute,
} as any)
const OwnerRepoPullsNewRoute = OwnerRepoPullsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRepoPullsRoute,
} as any)
const OwnerRepoReleasesIndexRoute = OwnerRepoReleasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoReleasesRoute,
} as any)
const OwnerRepoReleasesTagRoute = OwnerRepoReleasesTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => OwnerRepoReleasesRoute,
} as any)
const OwnerRepoReleasesNewRoute = OwnerRepoReleasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRepoReleasesRoute,
} as any)
const OwnerRepoSettingsActionsRoute =
  OwnerRepoSettingsActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => OwnerRepoSettingsRoute,
  } as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoUploadSplatRoute = OwnerRepoUploadSplatRouteImport.update({
  id: '/upload/$',
  path: '/upload/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const SettingsTokensNewIndexRoute = SettingsTokensNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTokensNewRoute,
} as any)
const SettingsTokensNewFineGrainedRoute =
  SettingsTokensNewFineGrainedRouteImport.update({
    id: '/fine-grained',
    path: '/fine-grained',
    getParentRoute: () => SettingsTokensNewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/packages': typeof OwnerPackagesRoute
  '/$owner/settings': typeof OwnerSettingsRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/lfs': typeof AdminLfsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/runners': typeof AdminRunnersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/emails': typeof SettingsEmailsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/settings/tokens': typeof SettingsTokensRouteWithChildren
  '/setup/credentials': typeof SetupCredentialsRoute
  '/$owner/': typeof OwnerIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsRouteWithChildren
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/fork': typeof OwnerRepoForkRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRouteWithChildren
  '/$owner/$repo/search': typeof OwnerRepoSearchRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRouteWithChildren
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/settings/labels': typeof OwnerSettingsLabelsRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/settings/tokens/new': typeof SettingsTokensNewRouteWithChildren
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/settings/': typeof OwnerSettingsIndexRoute
  '/settings/tokens/': typeof SettingsTokensIndexRoute
  '/$owner/$repo/actions/$run': typeof OwnerRepoActionsRunRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/delete/$': typeof OwnerRepoDeleteSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/issues/labels': typeof OwnerRepoIssuesLabelsRoute
  '/$owner/$repo/issues/new': typeof OwnerRepoIssuesNewRoute
  '/$owner/$repo/mkdir/$': typeof OwnerRepoMkdirSplatRoute
  '/$owner/$repo/new/$': typeof OwnerRepoNewSplatRoute
  '/$owner/$repo/pull/$n': typeof OwnerRepoPullNRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/releases/$tag': typeof OwnerRepoReleasesTagRoute
  '/$owner/$repo/releases/new': typeof OwnerRepoReleasesNewRoute
  '/$owner/$repo/settings/actions': typeof OwnerRepoSettingsActionsRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/upload/$': typeof OwnerRepoUploadSplatRoute
  '/settings/tokens/new/fine-grained': typeof SettingsTokensNewFineGrainedRoute
  '/$owner/$repo/actions/': typeof OwnerRepoActionsIndexRoute
  '/$owner/$repo/issues/': typeof OwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
  '/$owner/$repo/releases/': typeof OwnerRepoReleasesIndexRoute
  '/settings/tokens/new/': typeof SettingsTokensNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/$owner/packages': typeof OwnerPackagesRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/lfs': typeof AdminLfsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/runners': typeof AdminRunnersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/emails': typeof SettingsEmailsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/setup/credentials': typeof SetupCredentialsRoute
  '/$owner': typeof OwnerIndexRoute
  '/setup': typeof SetupIndexRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/fork': typeof OwnerRepoForkRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/search': typeof OwnerRepoSearchRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRouteWithChildren
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/settings/labels': typeof OwnerSettingsLabelsRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/settings': typeof OwnerSettingsIndexRoute
  '/settings/tokens': typeof SettingsTokensIndexRoute
  '/$owner/$repo/actions/$run': typeof OwnerRepoActionsRunRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/delete/$': typeof OwnerRepoDeleteSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/issues/labels': typeof OwnerRepoIssuesLabelsRoute
  '/$owner/$repo/issues/new': typeof OwnerRepoIssuesNewRoute
  '/$owner/$repo/mkdir/$': typeof OwnerRepoMkdirSplatRoute
  '/$owner/$repo/new/$': typeof OwnerRepoNewSplatRoute
  '/$owner/$repo/pull/$n': typeof OwnerRepoPullNRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/releases/$tag': typeof OwnerRepoReleasesTagRoute
  '/$owner/$repo/releases/new': typeof OwnerRepoReleasesNewRoute
  '/$owner/$repo/settings/actions': typeof OwnerRepoSettingsActionsRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/upload/$': typeof OwnerRepoUploadSplatRoute
  '/settings/tokens/new/fine-grained': typeof SettingsTokensNewFineGrainedRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsIndexRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsIndexRoute
  '/$owner/$repo/releases': typeof OwnerRepoReleasesIndexRoute
  '/settings/tokens/new': typeof SettingsTokensNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRouteWithChildren
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/verify': typeof VerifyRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/packages': typeof OwnerPackagesRoute
  '/$owner/settings': typeof OwnerSettingsRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/lfs': typeof AdminLfsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/runners': typeof AdminRunnersRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/emails': typeof SettingsEmailsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/ssh-keys': typeof SettingsSshKeysRoute
  '/settings/tokens': typeof SettingsTokensRouteWithChildren
  '/setup/credentials': typeof SetupCredentialsRoute
  '/$owner/': typeof OwnerIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/$owner/$repo/actions': typeof OwnerRepoActionsRouteWithChildren
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/branches': typeof OwnerRepoBranchesRoute
  '/$owner/$repo/fork': typeof OwnerRepoForkRoute
  '/$owner/$repo/forks': typeof OwnerRepoForksRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/packages': typeof OwnerRepoPackagesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRouteWithChildren
  '/$owner/$repo/search': typeof OwnerRepoSearchRoute
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRouteWithChildren
  '/$owner/$repo/stargazers': typeof OwnerRepoStargazersRoute
  '/$owner/$repo/tags': typeof OwnerRepoTagsRoute
  '/$owner/$repo/watchers': typeof OwnerRepoWatchersRoute
  '/$owner/settings/labels': typeof OwnerSettingsLabelsRoute
  '/$owner/settings/members': typeof OwnerSettingsMembersRoute
  '/settings/tokens/new': typeof SettingsTokensNewRouteWithChildren
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/settings/': typeof OwnerSettingsIndexRoute
  '/settings/tokens/': typeof SettingsTokensIndexRoute
  '/$owner/$repo/actions/$run': typeof OwnerRepoActionsRunRoute
  '/$owner/$repo/blame/$': typeof OwnerRepoBlameSplatRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof OwnerRepoCommitShaRoute
  '/$owner/$repo/commits/$': typeof OwnerRepoCommitsSplatRoute
  '/$owner/$repo/compare/$': typeof OwnerRepoCompareSplatRoute
  '/$owner/$repo/delete/$': typeof OwnerRepoDeleteSplatRoute
  '/$owner/$repo/edit/$': typeof OwnerRepoEditSplatRoute
  '/$owner/$repo/issues/$n': typeof OwnerRepoIssuesNRoute
  '/$owner/$repo/issues/labels': typeof OwnerRepoIssuesLabelsRoute
  '/$owner/$repo/issues/new': typeof OwnerRepoIssuesNewRoute
  '/$owner/$repo/mkdir/$': typeof OwnerRepoMkdirSplatRoute
  '/$owner/$repo/new/$': typeof OwnerRepoNewSplatRoute
  '/$owner/$repo/pull/$n': typeof OwnerRepoPullNRoute
  '/$owner/$repo/pulls/new': typeof OwnerRepoPullsNewRoute
  '/$owner/$repo/releases/$tag': typeof OwnerRepoReleasesTagRoute
  '/$owner/$repo/releases/new': typeof OwnerRepoReleasesNewRoute
  '/$owner/$repo/settings/actions': typeof OwnerRepoSettingsActionsRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
  '/$owner/$repo/upload/$': typeof OwnerRepoUploadSplatRoute
  '/settings/tokens/new/fine-grained': typeof SettingsTokensNewFineGrainedRoute
  '/$owner/$repo/actions/': typeof OwnerRepoActionsIndexRoute
  '/$owner/$repo/issues/': typeof OwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls/': typeof OwnerRepoPullsIndexRoute
  '/$owner/$repo/releases/': typeof OwnerRepoReleasesIndexRoute
  '/settings/tokens/new/': typeof SettingsTokensNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/new'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/setup'
    | '/signup'
    | '/status'
    | '/verify'
    | '/$owner/$repo'
    | '/$owner/packages'
    | '/$owner/settings'
    | '/admin/auth'
    | '/admin/lfs'
    | '/admin/packages'
    | '/admin/runners'
    | '/admin/templates'
    | '/admin/users'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/emails'
    | '/settings/general'
    | '/settings/profile'
    | '/settings/ssh-keys'
    | '/settings/tokens'
    | '/setup/credentials'
    | '/$owner/'
    | '/setup/'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/fork'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/search'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/settings/labels'
    | '/$owner/settings/members'
    | '/settings/tokens/new'
    | '/$owner/$repo/'
    | '/$owner/settings/'
    | '/settings/tokens/'
    | '/$owner/$repo/actions/$run'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/delete/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/issues/labels'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/mkdir/$'
    | '/$owner/$repo/new/$'
    | '/$owner/$repo/pull/$n'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/releases/$tag'
    | '/$owner/$repo/releases/new'
    | '/$owner/$repo/settings/actions'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/upload/$'
    | '/settings/tokens/new/fine-grained'
    | '/$owner/$repo/actions/'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/pulls/'
    | '/$owner/$repo/releases/'
    | '/settings/tokens/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/new'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/status'
    | '/verify'
    | '/$owner/packages'
    | '/admin/auth'
    | '/admin/lfs'
    | '/admin/packages'
    | '/admin/runners'
    | '/admin/templates'
    | '/admin/users'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/emails'
    | '/settings/general'
    | '/settings/profile'
    | '/settings/ssh-keys'
    | '/setup/credentials'
    | '/$owner'
    | '/setup'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/fork'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/search'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/settings/labels'
    | '/$owner/settings/members'
    | '/$owner/$repo'
    | '/$owner/settings'
    | '/settings/tokens'
    | '/$owner/$repo/actions/$run'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/delete/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/issues/labels'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/mkdir/$'
    | '/$owner/$repo/new/$'
    | '/$owner/$repo/pull/$n'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/releases/$tag'
    | '/$owner/$repo/releases/new'
    | '/$owner/$repo/settings/actions'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/upload/$'
    | '/settings/tokens/new/fine-grained'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/settings/tokens/new'
  id:
    | '__root__'
    | '/'
    | '/$owner'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/new'
    | '/notifications'
    | '/reset-password'
    | '/search'
    | '/setup'
    | '/signup'
    | '/status'
    | '/verify'
    | '/$owner/$repo'
    | '/$owner/packages'
    | '/$owner/settings'
    | '/admin/auth'
    | '/admin/lfs'
    | '/admin/packages'
    | '/admin/runners'
    | '/admin/templates'
    | '/admin/users'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/emails'
    | '/settings/general'
    | '/settings/profile'
    | '/settings/ssh-keys'
    | '/settings/tokens'
    | '/setup/credentials'
    | '/$owner/'
    | '/setup/'
    | '/$owner/$repo/actions'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/fork'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/packages'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/search'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stargazers'
    | '/$owner/$repo/tags'
    | '/$owner/$repo/watchers'
    | '/$owner/settings/labels'
    | '/$owner/settings/members'
    | '/settings/tokens/new'
    | '/$owner/$repo/'
    | '/$owner/settings/'
    | '/settings/tokens/'
    | '/$owner/$repo/actions/$run'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/commits/$'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/delete/$'
    | '/$owner/$repo/edit/$'
    | '/$owner/$repo/issues/$n'
    | '/$owner/$repo/issues/labels'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/mkdir/$'
    | '/$owner/$repo/new/$'
    | '/$owner/$repo/pull/$n'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/releases/$tag'
    | '/$owner/$repo/releases/new'
    | '/$owner/$repo/settings/actions'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/upload/$'
    | '/settings/tokens/new/fine-grained'
    | '/$owner/$repo/actions/'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/pulls/'
    | '/$owner/$repo/releases/'
    | '/settings/tokens/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRouteWithChildren
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  VerifyRoute: typeof VerifyRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminLfsRoute: typeof AdminLfsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminRunnersRoute: typeof AdminRunnersRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  OrgsNewRoute: typeof OrgsNewRoute
  SettingsEmailsRoute: typeof SettingsEmailsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSshKeysRoute: typeof SettingsSshKeysRoute
  SettingsTokensRoute: typeof SettingsTokensRouteWithChildren
}

declare module '@octanejs/tanstack-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner': {
      id: '/$owner'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/$owner/packages': {
      id: '/$owner/packages'
      path: '/packages'
      fullPath: '/$owner/packages'
      preLoaderRoute: typeof OwnerPackagesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/$owner/settings': {
      id: '/$owner/settings'
      path: '/settings'
      fullPath: '/$owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lfs': {
      id: '/admin/lfs'
      path: '/admin/lfs'
      fullPath: '/admin/lfs'
      preLoaderRoute: typeof AdminLfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/runners': {
      id: '/admin/runners'
      path: '/admin/runners'
      fullPath: '/admin/runners'
      preLoaderRoute: typeof AdminRunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/emails': {
      id: '/settings/emails'
      path: '/settings/emails'
      fullPath: '/settings/emails'
      preLoaderRoute: typeof SettingsEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ssh-keys': {
      id: '/settings/ssh-keys'
      path: '/settings/ssh-keys'
      fullPath: '/settings/ssh-keys'
      preLoaderRoute: typeof SettingsSshKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/credentials': {
      id: '/setup/credentials'
      path: '/credentials'
      fullPath: '/setup/credentials'
      preLoaderRoute: typeof SetupCredentialsRouteImport
      parentRoute: typeof SetupRoute
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/actions': {
      id: '/$owner/$repo/actions'
      path: '/actions'
      fullPath: '/$owner/$repo/actions'
      preLoaderRoute: typeof OwnerRepoActionsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/activity': {
      id: '/$owner/$repo/activity'
      path: '/activity'
      fullPath: '/$owner/$repo/activity'
      preLoaderRoute: typeof OwnerRepoActivityRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/branches': {
      id: '/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof OwnerRepoBranchesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/fork': {
      id: '/$owner/$repo/fork'
      path: '/fork'
      fullPath: '/$owner/$repo/fork'
      preLoaderRoute: typeof OwnerRepoForkRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/forks': {
      id: '/$owner/$repo/forks'
      path: '/forks'
      fullPath: '/$owner/$repo/forks'
      preLoaderRoute: typeof OwnerRepoForksRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/packages': {
      id: '/$owner/$repo/packages'
      path: '/packages'
      fullPath: '/$owner/$repo/packages'
      preLoaderRoute: typeof OwnerRepoPackagesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/releases': {
      id: '/$owner/$repo/releases'
      path: '/releases'
      fullPath: '/$owner/$repo/releases'
      preLoaderRoute: typeof OwnerRepoReleasesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/search': {
      id: '/$owner/$repo/search'
      path: '/search'
      fullPath: '/$owner/$repo/search'
      preLoaderRoute: typeof OwnerRepoSearchRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/stargazers': {
      id: '/$owner/$repo/stargazers'
      path: '/stargazers'
      fullPath: '/$owner/$repo/stargazers'
      preLoaderRoute: typeof OwnerRepoStargazersRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/tags': {
      id: '/$owner/$repo/tags'
      path: '/tags'
      fullPath: '/$owner/$repo/tags'
      preLoaderRoute: typeof OwnerRepoTagsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/watchers': {
      id: '/$owner/$repo/watchers'
      path: '/watchers'
      fullPath: '/$owner/$repo/watchers'
      preLoaderRoute: typeof OwnerRepoWatchersRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/settings/': {
      id: '/$owner/settings/'
      path: '/'
      fullPath: '/$owner/settings/'
      preLoaderRoute: typeof OwnerSettingsIndexRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/$owner/settings/labels': {
      id: '/$owner/settings/labels'
      path: '/labels'
      fullPath: '/$owner/settings/labels'
      preLoaderRoute: typeof OwnerSettingsLabelsRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/$owner/settings/members': {
      id: '/$owner/settings/members'
      path: '/members'
      fullPath: '/$owner/settings/members'
      preLoaderRoute: typeof OwnerSettingsMembersRouteImport
      parentRoute: typeof OwnerSettingsRoute
    }
    '/settings/tokens/': {
      id: '/settings/tokens/'
      path: '/'
      fullPath: '/settings/tokens/'
      preLoaderRoute: typeof SettingsTokensIndexRouteImport
      parentRoute: typeof SettingsTokensRoute
    }
    '/settings/tokens/new': {
      id: '/settings/tokens/new'
      path: '/new'
      fullPath: '/settings/tokens/new'
      preLoaderRoute: typeof SettingsTokensNewRouteImport
      parentRoute: typeof SettingsTokensRoute
    }
    '/$owner/$repo/actions/': {
      id: '/$owner/$repo/actions/'
      path: '/'
      fullPath: '/$owner/$repo/actions/'
      preLoaderRoute: typeof OwnerRepoActionsIndexRouteImport
      parentRoute: typeof OwnerRepoActionsRoute
    }
    '/$owner/$repo/actions/$run': {
      id: '/$owner/$repo/actions/$run'
      path: '/$run'
      fullPath: '/$owner/$repo/actions/$run'
      preLoaderRoute: typeof OwnerRepoActionsRunRouteImport
      parentRoute: typeof OwnerRepoActionsRoute
    }
    '/$owner/$repo/blame/$': {
      id: '/$owner/$repo/blame/$'
      path: '/blame/$'
      fullPath: '/$owner/$repo/blame/$'
      preLoaderRoute: typeof OwnerRepoBlameSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commit/$sha': {
      id: '/$owner/$repo/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/$owner/$repo/commit/$sha'
      preLoaderRoute: typeof OwnerRepoCommitShaRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits/$': {
      id: '/$owner/$repo/commits/$'
      path: '/commits/$'
      fullPath: '/$owner/$repo/commits/$'
      preLoaderRoute: typeof OwnerRepoCommitsSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/compare/$': {
      id: '/$owner/$repo/compare/$'
      path: '/compare/$'
      fullPath: '/$owner/$repo/compare/$'
      preLoaderRoute: typeof OwnerRepoCompareSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/delete/$': {
      id: '/$owner/$repo/delete/$'
      path: '/delete/$'
      fullPath: '/$owner/$repo/delete/$'
      preLoaderRoute: typeof OwnerRepoDeleteSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/edit/$': {
      id: '/$owner/$repo/edit/$'
      path: '/edit/$'
      fullPath: '/$owner/$repo/edit/$'
      preLoaderRoute: typeof OwnerRepoEditSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues/': {
      id: '/$owner/$repo/issues/'
      path: '/'
      fullPath: '/$owner/$repo/issues/'
      preLoaderRoute: typeof OwnerRepoIssuesIndexRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/issues/$n': {
      id: '/$owner/$repo/issues/$n'
      path: '/$n'
      fullPath: '/$owner/$repo/issues/$n'
      preLoaderRoute: typeof OwnerRepoIssuesNRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/issues/labels': {
      id: '/$owner/$repo/issues/labels'
      path: '/labels'
      fullPath: '/$owner/$repo/issues/labels'
      preLoaderRoute: typeof OwnerRepoIssuesLabelsRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/issues/new': {
      id: '/$owner/$repo/issues/new'
      path: '/new'
      fullPath: '/$owner/$repo/issues/new'
      preLoaderRoute: typeof OwnerRepoIssuesNewRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/mkdir/$': {
      id: '/$owner/$repo/mkdir/$'
      path: '/mkdir/$'
      fullPath: '/$owner/$repo/mkdir/$'
      preLoaderRoute: typeof OwnerRepoMkdirSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/new/$': {
      id: '/$owner/$repo/new/$'
      path: '/new/$'
      fullPath: '/$owner/$repo/new/$'
      preLoaderRoute: typeof OwnerRepoNewSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pull/$n': {
      id: '/$owner/$repo/pull/$n'
      path: '/pull/$n'
      fullPath: '/$owner/$repo/pull/$n'
      preLoaderRoute: typeof OwnerRepoPullNRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls/': {
      id: '/$owner/$repo/pulls/'
      path: '/'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof OwnerRepoPullsIndexRouteImport
      parentRoute: typeof OwnerRepoPullsRoute
    }
    '/$owner/$repo/pulls/new': {
      id: '/$owner/$repo/pulls/new'
      path: '/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof OwnerRepoPullsNewRouteImport
      parentRoute: typeof OwnerRepoPullsRoute
    }
    '/$owner/$repo/releases/': {
      id: '/$owner/$repo/releases/'
      path: '/'
      fullPath: '/$owner/$repo/releases/'
      preLoaderRoute: typeof OwnerRepoReleasesIndexRouteImport
      parentRoute: typeof OwnerRepoReleasesRoute
    }
    '/$owner/$repo/releases/$tag': {
      id: '/$owner/$repo/releases/$tag'
      path: '/$tag'
      fullPath: '/$owner/$repo/releases/$tag'
      preLoaderRoute: typeof OwnerRepoReleasesTagRouteImport
      parentRoute: typeof OwnerRepoReleasesRoute
    }
    '/$owner/$repo/releases/new': {
      id: '/$owner/$repo/releases/new'
      path: '/new'
      fullPath: '/$owner/$repo/releases/new'
      preLoaderRoute: typeof OwnerRepoReleasesNewRouteImport
      parentRoute: typeof OwnerRepoReleasesRoute
    }
    '/$owner/$repo/settings/actions': {
      id: '/$owner/$repo/settings/actions'
      path: '/actions'
      fullPath: '/$owner/$repo/settings/actions'
      preLoaderRoute: typeof OwnerRepoSettingsActionsRouteImport
      parentRoute: typeof OwnerRepoSettingsRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/upload/$': {
      id: '/$owner/$repo/upload/$'
      path: '/upload/$'
      fullPath: '/$owner/$repo/upload/$'
      preLoaderRoute: typeof OwnerRepoUploadSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/settings/tokens/new/': {
      id: '/settings/tokens/new/'
      path: '/'
      fullPath: '/settings/tokens/new/'
      preLoaderRoute: typeof SettingsTokensNewIndexRouteImport
      parentRoute: typeof SettingsTokensNewRoute
    }
    '/settings/tokens/new/fine-grained': {
      id: '/settings/tokens/new/fine-grained'
      path: '/fine-grained'
      fullPath: '/settings/tokens/new/fine-grained'
      preLoaderRoute: typeof SettingsTokensNewFineGrainedRouteImport
      parentRoute: typeof SettingsTokensNewRoute
    }
  }
}

interface OwnerRepoActionsRouteChildren {
  OwnerRepoActionsRunRoute: typeof OwnerRepoActionsRunRoute
  OwnerRepoActionsIndexRoute: typeof OwnerRepoActionsIndexRoute
}

const OwnerRepoActionsRouteChildren: OwnerRepoActionsRouteChildren = {
  OwnerRepoActionsRunRoute: OwnerRepoActionsRunRoute,
  OwnerRepoActionsIndexRoute: OwnerRepoActionsIndexRoute,
}

const OwnerRepoActionsRouteWithChildren =
  OwnerRepoActionsRoute._addFileChildren(OwnerRepoActionsRouteChildren)

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesNRoute: typeof OwnerRepoIssuesNRoute
  OwnerRepoIssuesLabelsRoute: typeof OwnerRepoIssuesLabelsRoute
  OwnerRepoIssuesNewRoute: typeof OwnerRepoIssuesNewRoute
  OwnerRepoIssuesIndexRoute: typeof OwnerRepoIssuesIndexRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesNRoute: OwnerRepoIssuesNRoute,
  OwnerRepoIssuesLabelsRoute: OwnerRepoIssuesLabelsRoute,
  OwnerRepoIssuesNewRoute: OwnerRepoIssuesNewRoute,
  OwnerRepoIssuesIndexRoute: OwnerRepoIssuesIndexRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface OwnerRepoPullsRouteChildren {
  OwnerRepoPullsNewRoute: typeof OwnerRepoPullsNewRoute
  OwnerRepoPullsIndexRoute: typeof OwnerRepoPullsIndexRoute
}

const OwnerRepoPullsRouteChildren: OwnerRepoPullsRouteChildren = {
  OwnerRepoPullsNewRoute: OwnerRepoPullsNewRoute,
  OwnerRepoPullsIndexRoute: OwnerRepoPullsIndexRoute,
}

const OwnerRepoPullsRouteWithChildren = OwnerRepoPullsRoute._addFileChildren(
  OwnerRepoPullsRouteChildren,
)

interface OwnerRepoReleasesRouteChildren {
  OwnerRepoReleasesTagRoute: typeof OwnerRepoReleasesTagRoute
  OwnerRepoReleasesNewRoute: typeof OwnerRepoReleasesNewRoute
  OwnerRepoReleasesIndexRoute: typeof OwnerRepoReleasesIndexRoute
}

const OwnerRepoReleasesRouteChildren: OwnerRepoReleasesRouteChildren = {
  OwnerRepoReleasesTagRoute: OwnerRepoReleasesTagRoute,
  OwnerRepoReleasesNewRoute: OwnerRepoReleasesNewRoute,
  OwnerRepoReleasesIndexRoute: OwnerRepoReleasesIndexRoute,
}

const OwnerRepoReleasesRouteWithChildren =
  OwnerRepoReleasesRoute._addFileChildren(OwnerRepoReleasesRouteChildren)

interface OwnerRepoSettingsRouteChildren {
  OwnerRepoSettingsActionsRoute: typeof OwnerRepoSettingsActionsRoute
}

const OwnerRepoSettingsRouteChildren: OwnerRepoSettingsRouteChildren = {
  OwnerRepoSettingsActionsRoute: OwnerRepoSettingsActionsRoute,
}

const OwnerRepoSettingsRouteWithChildren =
  OwnerRepoSettingsRoute._addFileChildren(OwnerRepoSettingsRouteChildren)

interface OwnerRepoRouteChildren {
  OwnerRepoActionsRoute: typeof OwnerRepoActionsRouteWithChildren
  OwnerRepoActivityRoute: typeof OwnerRepoActivityRoute
  OwnerRepoBranchesRoute: typeof OwnerRepoBranchesRoute
  OwnerRepoForkRoute: typeof OwnerRepoForkRoute
  OwnerRepoForksRoute: typeof OwnerRepoForksRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoPackagesRoute: typeof OwnerRepoPackagesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRouteWithChildren
  OwnerRepoReleasesRoute: typeof OwnerRepoReleasesRouteWithChildren
  OwnerRepoSearchRoute: typeof OwnerRepoSearchRoute
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRouteWithChildren
  OwnerRepoStargazersRoute: typeof OwnerRepoStargazersRoute
  OwnerRepoTagsRoute: typeof OwnerRepoTagsRoute
  OwnerRepoWatchersRoute: typeof OwnerRepoWatchersRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlameSplatRoute: typeof OwnerRepoBlameSplatRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoCommitShaRoute: typeof OwnerRepoCommitShaRoute
  OwnerRepoCommitsSplatRoute: typeof OwnerRepoCommitsSplatRoute
  OwnerRepoCompareSplatRoute: typeof OwnerRepoCompareSplatRoute
  OwnerRepoDeleteSplatRoute: typeof OwnerRepoDeleteSplatRoute
  OwnerRepoEditSplatRoute: typeof OwnerRepoEditSplatRoute
  OwnerRepoMkdirSplatRoute: typeof OwnerRepoMkdirSplatRoute
  OwnerRepoNewSplatRoute: typeof OwnerRepoNewSplatRoute
  OwnerRepoPullNRoute: typeof OwnerRepoPullNRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
  OwnerRepoUploadSplatRoute: typeof OwnerRepoUploadSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoActionsRoute: OwnerRepoActionsRouteWithChildren,
  OwnerRepoActivityRoute: OwnerRepoActivityRoute,
  OwnerRepoBranchesRoute: OwnerRepoBranchesRoute,
  OwnerRepoForkRoute: OwnerRepoForkRoute,
  OwnerRepoForksRoute: OwnerRepoForksRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoPackagesRoute: OwnerRepoPackagesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRouteWithChildren,
  OwnerRepoReleasesRoute: OwnerRepoReleasesRouteWithChildren,
  OwnerRepoSearchRoute: OwnerRepoSearchRoute,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRouteWithChildren,
  OwnerRepoStargazersRoute: OwnerRepoStargazersRoute,
  OwnerRepoTagsRoute: OwnerRepoTagsRoute,
  OwnerRepoWatchersRoute: OwnerRepoWatchersRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlameSplatRoute: OwnerRepoBlameSplatRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoCommitShaRoute: OwnerRepoCommitShaRoute,
  OwnerRepoCommitsSplatRoute: OwnerRepoCommitsSplatRoute,
  OwnerRepoCompareSplatRoute: OwnerRepoCompareSplatRoute,
  OwnerRepoDeleteSplatRoute: OwnerRepoDeleteSplatRoute,
  OwnerRepoEditSplatRoute: OwnerRepoEditSplatRoute,
  OwnerRepoMkdirSplatRoute: OwnerRepoMkdirSplatRoute,
  OwnerRepoNewSplatRoute: OwnerRepoNewSplatRoute,
  OwnerRepoPullNRoute: OwnerRepoPullNRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
  OwnerRepoUploadSplatRoute: OwnerRepoUploadSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

interface OwnerSettingsRouteChildren {
  OwnerSettingsLabelsRoute: typeof OwnerSettingsLabelsRoute
  OwnerSettingsMembersRoute: typeof OwnerSettingsMembersRoute
  OwnerSettingsIndexRoute: typeof OwnerSettingsIndexRoute
}

const OwnerSettingsRouteChildren: OwnerSettingsRouteChildren = {
  OwnerSettingsLabelsRoute: OwnerSettingsLabelsRoute,
  OwnerSettingsMembersRoute: OwnerSettingsMembersRoute,
  OwnerSettingsIndexRoute: OwnerSettingsIndexRoute,
}

const OwnerSettingsRouteWithChildren = OwnerSettingsRoute._addFileChildren(
  OwnerSettingsRouteChildren,
)

interface OwnerRouteChildren {
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  OwnerPackagesRoute: typeof OwnerPackagesRoute
  OwnerSettingsRoute: typeof OwnerSettingsRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  OwnerPackagesRoute: OwnerPackagesRoute,
  OwnerSettingsRoute: OwnerSettingsRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface SetupRouteChildren {
  SetupCredentialsRoute: typeof SetupCredentialsRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCredentialsRoute: SetupCredentialsRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface SettingsTokensNewRouteChildren {
  SettingsTokensNewFineGrainedRoute: typeof SettingsTokensNewFineGrainedRoute
  SettingsTokensNewIndexRoute: typeof SettingsTokensNewIndexRoute
}

const SettingsTokensNewRouteChildren: SettingsTokensNewRouteChildren = {
  SettingsTokensNewFineGrainedRoute: SettingsTokensNewFineGrainedRoute,
  SettingsTokensNewIndexRoute: SettingsTokensNewIndexRoute,
}

const SettingsTokensNewRouteWithChildren =
  SettingsTokensNewRoute._addFileChildren(SettingsTokensNewRouteChildren)

interface SettingsTokensRouteChildren {
  SettingsTokensNewRoute: typeof SettingsTokensNewRouteWithChildren
  SettingsTokensIndexRoute: typeof SettingsTokensIndexRoute
}

const SettingsTokensRouteChildren: SettingsTokensRouteChildren = {
  SettingsTokensNewRoute: SettingsTokensNewRouteWithChildren,
  SettingsTokensIndexRoute: SettingsTokensIndexRoute,
}

const SettingsTokensRouteWithChildren = SettingsTokensRoute._addFileChildren(
  SettingsTokensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRouteWithChildren,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  VerifyRoute: VerifyRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminLfsRoute: AdminLfsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminRunnersRoute: AdminRunnersRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  OrgsNewRoute: OrgsNewRoute,
  SettingsEmailsRoute: SettingsEmailsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSshKeysRoute: SettingsSshKeysRoute,
  SettingsTokensRoute: SettingsTokensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@octanejs/tanstack-start'
declare module '@octanejs/tanstack-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
